version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express-app
hooks:
  applicationstop:
    - location: scripts/application_stop.sh
      timeout: 300     

  beforeinstall:
    - location: scripts/before_install.sh
      timeout: 300

  applicationstart:
    - location: scripts/application_start.sh
      timeout: 300
